// lib/mockHumanAgents.ts

import { Agent } from "@/types";

// Mock Human Agents data
export const mockHumanAgents: Agent[] = [
  {
    id: "human-agent-1",
    name: "Dr. Sarah Johnson",
    description: "Board-certified physician providing telehealth consultations for startups and their employees. Specializing in occupational health and wellness programs.",
    category: "Healthcare",
    price: 400,
    rating: 4.9,
    ratingCount: 87,
    creatorId: "user-11",
    creatorName: "Dr. Johnson",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=sarah",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=doctor",
    purchasedBy: ["user-2", "user-3"],
    dateCreated: "2025-03-18T10:30:00.000Z",
    agentType: "human",
    experience: "15+ years",
    location: "Remote (US-based)",
    availability: "Mon-Fri, 9am-5pm EST",
    contactMethod: "Video call, Phone, Email",
    qualifications: ["MD", "Board Certified in Internal Medicine", "Telehealth Certified"]
  },
  {
    id: "human-agent-2",
    name: "James Wilson, CPA",
    description: "Certified Public Accountant specializing in startup finances, tax planning, and financial strategy. Help your startup optimize cash flow and prepare for funding rounds.",
    category: "Finance",
    price: 350,
    rating: 4.8,
    ratingCount: 62,
    creatorId: "user-12",
    creatorName: "JW Financial",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=james",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=accountant",
    purchasedBy: ["user-1"],
    dateCreated: "2025-03-15T14:45:00.000Z",
    agentType: "human",
    experience: "12 years",
    location: "Remote (Global)",
    availability: "Flexible scheduling",
    contactMethod: "Video call, Email, Shared documents",
    qualifications: ["CPA", "MBA Finance", "Series 65 Licensed"]
  },
  {
    id: "human-agent-3",
    name: "Elena Martinez, Esq.",
    description: "Corporate attorney specializing in startup law, IP protection, and contract review. Get expert legal guidance for your growing business.",
    category: "Legal Services",
    price: 500,
    rating: 4.9,
    ratingCount: 41,
    creatorId: "user-13",
    creatorName: "Martinez Legal",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=elena",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=lawyer",
    purchasedBy: [],
    dateCreated: "2025-02-28T09:15:00.000Z",
    agentType: "human",
    experience: "10 years",
    location: "Remote (US-based)",
    availability: "Mon-Fri, 10am-6pm PST",
    contactMethod: "Video call, Phone, Email",
    qualifications: ["JD", "Bar Certified", "Startup Law Specialist"]
  },
  {
    id: "human-agent-4",
    name: "Michael Chen",
    description: "Full-stack developer with expertise in React, Node.js, and cloud architecture. Available for consultation, code reviews, and technical strategy.",
    category: "Software Development",
    price: 300,
    rating: 4.7,
    ratingCount: 78,
    creatorId: "user-14",
    creatorName: "TechConsult",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=michael",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=developer",
    purchasedBy: ["user-1", "user-2", "user-5"],
    dateCreated: "2025-03-05T11:20:00.000Z",
    agentType: "human",
    experience: "8 years",
    location: "Remote (Global)",
    availability: "Flexible hours",
    contactMethod: "Video call, Slack, GitHub",
    qualifications: ["BS Computer Science", "AWS Certified", "Google Cloud Certified"]
  },
  {
    id: "human-agent-5",
    name: "Priya Sharma",
    description: "Digital marketing specialist with focus on startup growth, SEO, and social media strategy. Boost your online presence and customer acquisition.",
    category: "Marketing",
    price: 250,
    rating: 4.6,
    ratingCount: 56,
    creatorId: "user-15",
    creatorName: "GrowthHackers",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=priya",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=marketer",
    purchasedBy: ["user-3"],
    dateCreated: "2025-03-20T15:00:00.000Z",
    agentType: "human",
    experience: "7 years",
    location: "Remote (APAC/US friendly hours)",
    availability: "Weekdays, flexible hours",
    contactMethod: "Video call, Email, Slack",
    qualifications: ["Google Ads Certified", "Facebook Blueprint Certified", "HubSpot Certified"]
  },
  {
    id: "human-agent-6",
    name: "Robert Taylor",
    description: "HR consultant specializing in startup hiring, team building, and company culture development. Scale your team effectively.",
    category: "Human Resources",
    price: 280,
    rating: 4.5,
    ratingCount: 39,
    creatorId: "user-16",
    creatorName: "TalentForge",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=robert",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=hr",
    purchasedBy: ["user-2"],
    dateCreated: "2025-03-18T13:10:00.000Z",
    agentType: "human",
    experience: "9 years",
    location: "Remote (US-based)",
    availability: "Mon-Fri, 9am-6pm CST",
    contactMethod: "Video call, Phone, Email",
    qualifications: ["SHRM-CP", "MBA", "Talent Acquisition Specialist"]
  },
  {
    id: "human-agent-7",
    name: "David Kim",
    description: "Product management consultant helping startups define, build, and launch successful products. From idea to market with proven methodologies.",
    category: "Product Management",
    price: 400,
    rating: 4.8,
    ratingCount: 47,
    creatorId: "user-17",
    creatorName: "ProductLaunch",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=david",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=product",
    purchasedBy: ["user-1"],
    dateCreated: "2025-03-25T11:20:00.000Z",
    agentType: "human",
    experience: "11 years",
    location: "Remote (Global)",
    availability: "Flexible scheduling",
    contactMethod: "Video call, Slack, Project management tools",
    qualifications: ["PMP", "Certified Scrum Product Owner", "MBA"]
  },
  {
    id: "human-agent-8",
    name: "Sophia Rodriguez",
    description: "UX/UI designer specializing in user research, interface design, and usability testing for digital products and services.",
    category: "Design",
    price: 320,
    rating: 4.7,
    ratingCount: 53,
    creatorId: "user-18",
    creatorName: "DesignSprint",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=sophia",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=designer",
    purchasedBy: ["user-3", "user-5"],
    dateCreated: "2025-03-12T09:40:00.000Z",
    agentType: "human",
    experience: "6 years",
    location: "Remote (Americas/Europe)",
    availability: "Tue-Sat, flexible hours",
    contactMethod: "Video call, Figma, Slack",
    qualifications: ["BFA Design", "Nielsen Norman Group Certified", "Adobe Certified Expert"]
  },
  {
    id: "human-agent-9",
    name: "Thomas Wright",
    description: "Business strategy consultant with expertise in startup growth, market analysis, and competitive positioning. Navigate your path to success.",
    category: "Business Strategy",
    price: 450,
    rating: 4.8,
    ratingCount: 32,
    creatorId: "user-19",
    creatorName: "StrategyWorks",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=thomas",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=consultant",
    purchasedBy: [],
    dateCreated: "2025-03-17T14:30:00.000Z",
    agentType: "human",
    experience: "14 years",
    location: "Remote (Global)",
    availability: "By appointment",
    contactMethod: "Video call, Phone, Email, Onsite visits",
    qualifications: ["MBA", "Former VC Partner", "Management Consulting Background"]
  },
  {
    id: "human-agent-10",
    name: "Olivia Bennett",
    description: "Sales consultant helping startups build effective sales processes, pipelines, and teams. Increase your revenue and customer base.",
    category: "Sales",
    price: 350,
    rating: 4.6,
    ratingCount: 44,
    creatorId: "user-20",
    creatorName: "SalesAccelerator",
    creatorAvatarUrl: "https://api.dicebear.com/6.x/avataaars/svg?seed=olivia",
    imageUrl: "https://api.dicebear.com/6.x/personas/svg?seed=sales",
    purchasedBy: ["user-2", "user-4"],
    dateCreated: "2025-03-21T10:15:00.000Z",
    agentType: "human",
    experience: "10 years",
    location: "Remote (US/Europe)",
    availability: "Weekdays, 8am-7pm EST",
    contactMethod: "Video call, Phone, CRM integration",
    qualifications: ["Certified Sales Professional", "HubSpot Sales Certified", "Sandler Training"]
  }
];
