
import { ContestCategory } from "@/components/contests/ContestCard";

export const mockContests = [
  {
    id: 'contest-1',
    title: 'LeetCode Challenge: 30 Days of Code',
    description: 'Complete 30 coding challenges in 30 days to win big prizes. Improve your algorithmic skills and compete against other developers.',
    category: 'coding' as ContestCategory,
    entryFee: 50,
    prizePool: 5000,
    participants: 248,
    endDate: '2025-05-15',
    featured: true,
  },
  {
    id: 'contest-2',
    title: 'Financial Literacy Marathon',
    description: 'Test your financial knowledge in this 2-week contest. Answer daily quizzes and complete financial planning exercises.',
    category: 'finance' as ContestCategory,
    entryFee: 30,
    prizePool: 2500,
    participants: 156,
    endDate: '2025-04-30',
    featured: false,
  },
  {
    id: 'contest-3',
    title: 'Productivity Mastery Challenge',
    description: 'Track your productive hours, complete focused work sessions and build healthy productivity habits.',
    category: 'productivity' as ContestCategory,
    entryFee: 25,
    prizePool: 1800,
    participants: 312,
    endDate: '2025-05-07',
    featured: false,
  },
  {
    id: 'contest-4',
    title: 'Data Science Boot Camp',
    description: 'Learn data science and machine learning through hands-on projects. Submit your final project to compete for the prize.',
    category: 'learning' as ContestCategory,
    entryFee: 75,
    prizePool: 8000,
    participants: 124,
    endDate: '2025-06-01',
    featured: true,
  },
  {
    id: 'contest-5',
    title: 'Frontend Dev Showdown',
    description: 'Create beautiful and functional UI components and compete for the best implementation. Judged by industry experts.',
    category: 'coding' as ContestCategory,
    entryFee: 40,
    prizePool: 3500,
    participants: 175,
    endDate: '2025-05-22',
    featured: false,
  },
  {
    id: 'contest-6',
    title: 'Budget Challenge',
    description: 'Create and stick to a budget for 3 weeks. Track expenses and savings to win prizes.',
    category: 'finance' as ContestCategory,
    entryFee: 20,
    prizePool: 1200,
    participants: 298,
    endDate: '2025-04-25',
    featured: false,
  },
  {
    id: 'contest-7',
    title: 'Morning Routine Revolution',
    description: 'Build and maintain a productive morning routine for 21 days. Track your progress and share insights.',
    category: 'productivity' as ContestCategory,
    entryFee: 15,
    prizePool: 1000,
    participants: 423,
    endDate: '2025-05-10',
    featured: false,
  },
  {
    id: 'contest-8',
    title: 'AWS Certification Sprint',
    description: 'Prepare for and pass the AWS certification exam in 30 days. Get study materials, practice tests, and guidance.',
    category: 'learning' as ContestCategory,
    entryFee: 60,
    prizePool: 4500,
    participants: 198,
    endDate: '2025-05-20',
    featured: false,
  },
  // New contests
  {
    id: 'contest-9',
    title: 'Smart Contract Challenge',
    description: 'Develop innovative smart contracts for real-world applications. Showcase your blockchain development skills and win rewards.',
    category: 'coding' as ContestCategory,
    entryFee: 100,
    prizePool: 10000,
    participants: 87,
    endDate: '2025-06-15',
    featured: true,
    difficulty: 'advanced',
  },
  {
    id: 'contest-10',
    title: 'Crypto Trading Tournament',
    description: 'Compete in a simulated crypto trading environment. Use your market analysis skills to maximize portfolio returns.',
    category: 'finance' as ContestCategory,
    entryFee: 80,
    prizePool: 7500,
    participants: 142,
    endDate: '2025-05-30',
    featured: false,
  },
  {
    id: 'contest-11',
    title: 'Knowledge Graph Hackathon',
    description: 'Build a knowledge graph application that connects different domains of information in novel ways.',
    category: 'coding' as ContestCategory,
    entryFee: 65,
    prizePool: 6000,
    participants: 103,
    endDate: '2025-06-07',
    featured: false,
  },
  {
    id: 'contest-12',
    title: 'Focus Flow Marathon',
    description: 'Master the art of deep work and focus. Track your flow state sessions and compete for the longest streaks.',
    category: 'productivity' as ContestCategory,
    entryFee: 30,
    prizePool: 2200,
    participants: 267,
    endDate: '2025-05-12',
    featured: false,
  }
];
